### ISSUE TITLE
Username Mapping to support using YT Api Credentials

### ISSUE THREAD

**Issue by diegohb** [diegohb/pscm-youtrack-plugin#4]
I've tried running this using the username mapping field and it's not properly switching it over for yt ticket assignment and running commands.

When creating branch from task, I get this error:

![image](https://user-images.githubusercontent.com/3726681/45841942-4ec90980-bce9-11e8-9483-8131b6464f0f.png)

Error log:

> 8-09-20 15:23:38,650 PSIWKSTA01\diego DEBUG extensions - YouTrackService: GetPlasticTask PMAPS-31
> 2018-09-20 15:23:49,697 [REDACTED]\diego ERROR plastic - Plastic SCM client version: 7.0.16.2445
> 2018-09-20 15:23:49,698 [REDACTED]\diego ERROR plastic - 
> Error message: Command [for api] is invalid:Unknown command: Assignee expected: api
> 2018-09-20 15:23:49,699 [REDACTED]\diego DEBUG plastic - 
> StackTrace:    at YouTrackSharp.Issues.IssuesService.<ApplyCommand>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at MMG.PlasticExtensions.YouTrackPlugin.YouTrackService.<AssignIssue>d__17.MoveNext() in D:\[REDACTED]\pscm-youtrack-plugin\src\MMG.PlasticExtensions.YouTrackPlugin\YouTrackService.cs:line 234

**Comment by diegohb** [comment]
applied.
